# Generated by Django 4.2.9 on 2024-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название аэропорта')),
                ('code_iata', models.CharField(max_length=3, verbose_name='код ИАТА')),
                ('code_icao', models.CharField(max_length=4, verbose_name='код ИКАО')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('country', models.CharField(max_length=64, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('kind_service', models.CharField(choices=[('TRANSFER', 'Transfer'), ('BUSINES_LOUNGE', 'Busines Lounge'), ('PORTER', 'Porter'), ('CHILDREN', 'Children')], max_length=18)),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
