# Generated by Django 4.2.4 on 2024-06-23 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airports', '0002_services_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='kind_service',
            field=models.CharField(choices=[('MEET & ASSIST', 'Transfer'), ('FULL VIP', 'Fullvip'), ('FAST TRACK', 'Fasttrack')], max_length=18),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.services')),
            ],
            options={
                'verbose_name': 'Сервисы в корзине в корзине',
                'verbose_name_plural': 'Сервисы в корзине',
                'unique_together': {('cart', 'service')},
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.ManyToManyField(through='airports.CartItem', to='airports.services', verbose_name='Сервисы в корзине'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
